data.extend({
	{
		name = "residual-oil",
		icon = "__hydraulic_machines__/graphics/residual-oil.png",
		type = "fluid",
		subgroup = "fluid",
		default_temperature = 25,
		base_color = { 0.5, 0.13, 0 },
		flow_color = { 0.85, 0.6, 0.3 },
		order = "a[fluid]-b[oil]-dz[heavy-oil]",
	},
	{
		name = "naphtha",
		icon = "__hydraulic_machines__/graphics/naphtha.png",
		type = "fluid",
		subgroup = "fluid",
		default_temperature = 25,
		base_color = { 0.57, 0.33, 0 },
		flow_color = { 1, 0.73, 0.07 },
		order = "a[fluid]-b[oil]-bc[naphtha]",
	},
	{
		name = "gasoline",
		icon = "__hydraulic_machines__/graphics/gasoline.png",
		type = "fluid",
		subgroup = "fluid",
		default_temperature = 25,
		base_color = { 0.57, 0.33, 0 },
		flow_color = { 1, 0.73, 0.07 },
		order = "a[fluid]-b[oil]-bc[gasoline]",
	},
})
