require("__base__.prototypes.entity.pipecovers")
local item_sounds = require("__base__.prototypes.item_sounds")

local hit_effects = require("__base__.prototypes.entity.hit-effects")
local sounds = require("__base__.prototypes.entity.sounds")

data:extend({
	{
		name = "petochemical-processing",
		type = "recipe-category",
	},
})
data:extend({

	{
		type = "item",
		name = "hydraulic-petrochemical-plant",
		icon = "__hydraulic_machines__/graphics/hydraulic-petrochemical-plant/hydraulic-petrochemical-plant-icon.png",
		subgroup = "production-machine",
		color_hint = { text = "2" },
		order = "b[hydraulic-assembling-machine]",
		inventory_move_sound = item_sounds.mechanical_inventory_move,
		pick_sound = item_sounds.mechanical_inventory_pickup,
		drop_sound = item_sounds.mechanical_inventory_move,
		--default_import_location = "hydraulic_machines",
		weight = 50 * kg,
		place_result = "hydraulic-petrochemical-plant",
		stack_size = 50,
	},
	{
		type = "assembling-machine",
		name = "hydraulic-petrochemical-plant",
		icon = "__hydraulic_machines__/graphics/hydraulic-petrochemical-plant/hydraulic-petrochemical-plant-icon.png",
		flags = { "placeable-neutral", "player-creation" },
		minable = { mining_time = 0.2, result = "hydraulic-petrochemical-plant" },
		fast_replaceable_group = "hydraulic-petrochemical-plant",
		max_health = 350,
		corpse = "oil-refinery-remnants",
		dying_explosion = "oil-refinery-explosion",
		icon_draw_specification = { scale = 2, shift = { 0, -0.3 } },
		circuit_wire_max_distance = assembling_machine_circuit_wire_max_distance,
		circuit_connector = circuit_connector_definitions["oil-refinery"],
		--collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
		collision_box = { { -4.20, -4.20 }, { 4.20, 4.20 } },
		selection_box = { { -4.5, -4.5 }, { 4.5, 4.5 } },
		collision_mask = {
			layers = {
				item = true,
				object = true,
				player = true,
				water_tile = true,
				elevated_rail = true,
				is_object = true,
				is_lower_object = true,
				meltable = true,
			},
		},
		damaged_trigger_effect = hit_effects.entity(),
		drawing_box_vertical_extension = 0,
		module_slots = 5,
		allowed_effects = { "consumption", "speed", "productivity", "pollution" },
		crafting_categories = { "oil-processing", "petochemical-processing" },
		crafting_speed = 4,
		energy_source = {
			type = "fluid",
			burns_fluid = true, -- fluid used as power
			emissions_per_minute = { pollution = 2 },
			scale_fluid_usage = true,
			light_flicker = {
				color = { 0, 0, 0, 0 }, -- to remove default burner glow
			},
			fluid_box = {
				--pipe_picture = hydraulic_refinery_pipes(),
				pipe_covers = pipecoverspictures(),
				always_draw_covers = true,
				volume = 100,
				filter = "lubricant",
				pipe_connections = {
					{ direction = defines.direction.west, position = { -4, 0 } },
					{ direction = defines.direction.east, position = { 4, 0 } },
				},
				production_type = "input-output",
			},
		},
		energy_usage = "200kW",

		graphics_set = {
			animation = {
				layers = {
					{
						filename = "__hydraulic_machines__/graphics/hydraulic-petrochemical-plant/hydraulic-petrochemical-plant.png",
						priority = "high",
						width = 660,
						height = 700,
						frame_count = 1,
						line_length = 1,
						shift = util.by_pixel(0, -10),
						scale = 0.47,
					},
					{
						filename = "__base__/graphics/entity/assembling-machine-3/assembling-machine-3-shadow.png",
						priority = "high",
						width = 260,
						height = 162,
						frame_count = 1,
						line_length = 1,
						draw_as_shadow = true,
						shift = util.by_pixel(28, 4),
						scale = 0.5,
					},
				},
			},
			--animation = make_4way_animation_from_spritesheet({
			--	layers = {
			--		{
			--			filename = "__base__/graphics/entity/oil-refinery/oil-refinery.png",
			--			width = 386,
			--			height = 430,
			--			shift = util.by_pixel(0, -7.5),
			--			scale = 0.5,
			--		},
			--		{
			--			filename = "__base__/graphics/entity/oil-refinery/oil-refinery-shadow.png",
			--			width = 674,
			--			height = 426,
			--			shift = util.by_pixel(82.5, 26.5),
			--			draw_as_shadow = true,
			--			scale = 0.5,
			--		},
			--	},
			--}),

			working_visualisations = {
				{
					fadeout = true,
					constant_speed = true,
					north_position = util.by_pixel(15, -141),
					east_position = util.by_pixel(15, -141),
					south_position = util.by_pixel(15, -141),
					west_position = util.by_pixel(15, -141),
					animation = {
						filename = "__base__/graphics/entity/oil-refinery/oil-refinery-fire.png",
						line_length = 10,
						width = 40,
						height = 81,
						frame_count = 60,
						animation_speed = 0.75,
						scale = 0.5,
						draw_as_glow = true,
						shift = util.by_pixel(0, -14.25),
					},
				},
				{
					fadeout = true,
					constant_speed = true,
					north_position = util.by_pixel(-38, -125),
					east_position = util.by_pixel(-38, -125),
					south_position = util.by_pixel(-38, -125),
					west_position = util.by_pixel(-38, -125),
					animation = {
						filename = "__base__/graphics/entity/oil-refinery/oil-refinery-fire.png",
						line_length = 10,
						width = 40,
						height = 81,
						frame_count = 60,
						animation_speed = 0.75,
						scale = 0.5,
						draw_as_glow = true,
						shift = util.by_pixel(0, -14.25),
					},
				},
				{
					fadeout = true,
					constant_speed = true,
					north_position = util.by_pixel(129, 18),
					east_position = util.by_pixel(129, 18),
					south_position = util.by_pixel(129, 18),
					west_position = util.by_pixel(129, 18),
					animation = {
						filename = "__base__/graphics/entity/oil-refinery/oil-refinery-fire.png",
						line_length = 10,
						width = 40,
						height = 81,
						frame_count = 60,
						animation_speed = 0.75,
						scale = 0.5,
						draw_as_glow = true,
						shift = util.by_pixel(0, -14.25),
					},
				},
				{
					fadeout = true,
					constant_speed = true,
					north_position = util.by_pixel(-124, 14),
					east_position = util.by_pixel(-124, 14),
					south_position = util.by_pixel(-124, 14),
					west_position = util.by_pixel(-124, 14),
					animation = {
						filename = "__base__/graphics/entity/oil-refinery/oil-refinery-fire.png",
						line_length = 10,
						width = 40,
						height = 81,
						frame_count = 60,
						animation_speed = 0.75,
						scale = 0.5,
						draw_as_glow = true,
						shift = util.by_pixel(0, -14.25),
					},
				},

				{
					fadeout = true,
					north_animation = {
						filename = "__hydraulic_machines__/graphics/hydraulic-petrochemical-plant/hydraulic-petrochemical-plant-light.png",
						blend_mode = "additive",
						width = 660,
						height = 700,
						frame_count = 1,
						line_length = 1,
						shift = util.by_pixel(0, -10),
						scale = 0.47,
						draw_as_glow = true,
					},
					east_animation = {
						filename = "__hydraulic_machines__/graphics/hydraulic-petrochemical-plant/hydraulic-petrochemical-plant-light.png",
						blend_mode = "additive",
						width = 660,
						height = 700,
						frame_count = 1,
						line_length = 1,
						shift = util.by_pixel(0, -10),
						scale = 0.47,
						draw_as_glow = true,
					},
					south_animation = {
						filename = "__hydraulic_machines__/graphics/hydraulic-petrochemical-plant/hydraulic-petrochemical-plant-light.png",
						blend_mode = "additive",
						width = 660,
						height = 700,
						frame_count = 1,
						line_length = 1,
						shift = util.by_pixel(0, -10),
						scale = 0.47,
						draw_as_glow = true,
					},
					west_animation = {
						blend_mode = "additive",
						filename = "__hydraulic_machines__/graphics/hydraulic-petrochemical-plant/hydraulic-petrochemical-plant-light.png",
						width = 660,
						height = 700,
						frame_count = 1,
						line_length = 1,
						shift = util.by_pixel(0, -10),
						scale = 0.47,
						draw_as_glow = true,
					},
				},

				--				{
				--					fadeout = true,
				--					north_animation = {
				--						filename = "__base__/graphics/entity/oil-refinery/oil-refinery-light.png",
				--						width = 321,
				--						height = 205,
				--						blend_mode = "additive",
				--						draw_as_glow = true,
				--						shift = util.by_pixel(-1, -50),
				--						scale = 0.5,
				--					},
				--					east_animation = {
				--						filename = "__base__/graphics/entity/oil-refinery/oil-refinery-light.png",
				--						width = 321,
				--						x = 321,
				--						height = 205,
				--						blend_mode = "additive",
				--						draw_as_glow = true,
				--						shift = util.by_pixel(-1, -50),
				--						scale = 0.5,
				--					},
				--					south_animation = {
				--						filename = "__base__/graphics/entity/oil-refinery/oil-refinery-light.png",
				--						width = 321,
				--						x = 321 * 2,
				--						height = 205,
				--						blend_mode = "additive",
				--						draw_as_glow = true,
				--						shift = util.by_pixel(-1, -50),
				--						scale = 0.5,
				--					},
				--					west_animation = {
				--						filename = "__base__/graphics/entity/oil-refinery/oil-refinery-light.png",
				--						width = 321,
				--						x = 321 * 3,
				--						height = 205,
				--						blend_mode = "additive",
				--						draw_as_glow = true,
				--						shift = util.by_pixel(-1, -50),
				--						scale = 0.5,
				--					},
				--				},
			},
		},
		impact_category = "metal-large",
		open_sound = sounds.metal_large_open,
		close_sound = sounds.metal_large_close,
		working_sound = {
			sound = { filename = "__base__/sound/oil-refinery.ogg" },
			fade_in_ticks = 4,
			fade_out_ticks = 20,
		},
		fluid_boxes = {
			{
				production_type = "input",
				pipe_covers = pipecoverspictures(),
				volume = 1000,
				pipe_connections = {
					{
						flow_direction = "input",
						direction = defines.direction.south,
						position = { -2, 4 },
					},
				},
			},
			{
				production_type = "input",
				pipe_covers = pipecoverspictures(),
				volume = 1000,
				pipe_connections = {
					{
						flow_direction = "input",
						direction = defines.direction.south,
						position = { 0, 4 },
					},
				},
			},
			{
				production_type = "input",
				pipe_covers = pipecoverspictures(),
				volume = 1000,
				pipe_connections = {
					{
						flow_direction = "input",
						direction = defines.direction.south,
						position = { 2, 4 },
					},
				},
			},
			{
				production_type = "output",
				pipe_covers = pipecoverspictures(),
				volume = 100,
				pipe_connections = {
					{
						flow_direction = "output",
						direction = defines.direction.north,
						position = { -4, -4 },
					},
				},
			},
			{
				production_type = "output",
				pipe_covers = pipecoverspictures(),
				volume = 100,
				pipe_connections = {
					{
						flow_direction = "output",
						direction = defines.direction.north,
						position = { -2, -4 },
					},
				},
			},
			{
				production_type = "output",
				pipe_covers = pipecoverspictures(),
				volume = 100,
				pipe_connections = {
					{
						flow_direction = "output",
						direction = defines.direction.north,
						position = { 0, -4 },
					},
				},
			},
			{
				production_type = "output",
				pipe_covers = pipecoverspictures(),
				volume = 100,
				pipe_connections = {
					{
						flow_direction = "output",
						direction = defines.direction.north,
						position = { 2, -4 },
					},
				},
			},
			{
				production_type = "output",
				pipe_covers = pipecoverspictures(),
				volume = 100,
				pipe_connections = {
					{
						flow_direction = "output",
						direction = defines.direction.north,
						position = { 4, -4 },
					},
				},
			},
		},
	},
})
