local item_sounds = require("__base__.prototypes.item_sounds")
data:extend({
	{
		type = "module-category",
		name = "industrial",
	},
	{
		type = "module",
		name = "industrial-module",
		icon = "__hydraulic_machines__/graphics/industrial-module/industrial-module.png",
		subgroup = "module",
		color_hint = { text = "i" },
		category = "industrial",
		tier = 1,
		order = "c[industrial]-a[industrial-module-1]",
		inventory_move_sound = item_sounds.module_inventory_move,
		pick_sound = item_sounds.module_inventory_pickup,
		drop_sound = item_sounds.module_inventory_move,
		stack_size = 50,
		weight = 20 * kg,
		effect = {
			productivity = 0.08,
			consumption = 0.4,
			pollution = 0.1,
		},
	},
	{
		type = "module",
		name = "industrial-module-2",
		icon = "__hydraulic_machines__/graphics/industrial-module/industrial-module-2.png",
		subgroup = "module",
		color_hint = { text = "i" },
		category = "industrial",
		tier = 2,
		order = "c[industrial]-b[industrial-module-2]",
		inventory_move_sound = item_sounds.module_inventory_move,
		pick_sound = item_sounds.module_inventory_pickup,
		drop_sound = item_sounds.module_inventory_move,
		stack_size = 50,
		weight = 20 * kg,
		effect = {
			productivity = 0.12,
			consumption = 0.6,
			pollution = 0.14,
		},
	},
	{
		type = "module",
		name = "industrial-module-3",
		icon = "__hydraulic_machines__/graphics/industrial-module/industrial-module-3.png",
		subgroup = "module",
		color_hint = { text = "i" },
		category = "industrial",
		tier = 3,
		order = "c[industrial]-c[industrial-module-3]",
		inventory_move_sound = item_sounds.module_inventory_move,
		pick_sound = item_sounds.module_inventory_pickup,
		drop_sound = item_sounds.module_inventory_move,
		stack_size = 50,
		weight = 20 * kg,
		effect = {
			productivity = 0.2,
			consumption = 1.0,
			pollution = 0.2,
		},
	},
})

data:extend({
	{
		type = "recipe",
		name = "industrial-module",
		category = "hydraulic-assembling",
		enabled = false,
		ingredients = {
			{ type = "item", name = "productivity-module", amount = 4 },
			{ type = "item", name = "advanced-circuit", amount = 5 },
			{ type = "item", name = "electronic-circuit", amount = 5 },
		},
		energy_required = 15,
		results = { { type = "item", name = "industrial-module", amount = 1 } },
	},
	{
		type = "recipe",
		name = "industrial-module-2",
		category = "hydraulic-assembling",
		enabled = false,
		ingredients = {
			{ type = "item", name = "industrial-module", amount = 4 },
			{ type = "item", name = "productivity-module-2", amount = 4 },
			{ type = "item", name = "advanced-circuit", amount = 5 },
			{ type = "item", name = "processing-unit", amount = 5 },
		},
		energy_required = 30,
		results = { { type = "item", name = "industrial-module-2", amount = 1 } },
	},
	{
		type = "recipe",
		name = "industrial-module-3",
		category = "hydraulic-assembling",
		enabled = false,
		ingredients = {
			{ type = "item", name = "industrial-module-2", amount = 4 },
			{ type = "item", name = "productivity-module-3", amount = 4 },
			{ type = "item", name = "advanced-circuit", amount = 5 },
			{ type = "item", name = "processing-unit", amount = 5 },
		},
		energy_required = 60,
		results = { { type = "item", name = "industrial-module-3", amount = 1 } },
	},
})
